schema_version: 1
name: jboss.container.eap.galleon.config.mp
version: '1.0-elytron'
description: Install Galleon mp default configuration.

execute:
- script: configure.sh

modules:
  install:
  - name: jboss.container.eap.galleon.config.mp.common