schema_version: 1
name: jboss.container.eap.galleon.config.mp.common
version: '1.0'
description: Install Galleon descriptions and EAP s2i feature-pack for mp config

envs:
- name: S2I_FP_VERSION
  value: "4.0.0.Final"

execute:
- script: configure.sh
