schema_version: 1
name: jboss.container.config.eap
version: '7'
description: Shared EAP 7 base configuration
modules:
  install:
  - name: os-java-run
execute:
- script: prepare.sh
- script: configure.sh
  user: '185'
